name: Run My Git Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          pip install apprise

      - name: Run Script
        run: |
          node epic-games
